### ISSUE TITLE
Problem with files of the same name

### ISSUE THREAD

**Issue by jcelliott** [sjbach/lusty#93]
Steps to reproduce:

```
touch test.py
mkdir test
touch test/test.py
vim test.py test/test.py
<Open LustyExplorer>
```

Output (in LustyExplorer buffer):

```
.py|/test.py
```

Should be:

```
test.py|test/test.py
```

Tested with latest from master. If this is possibly a configuration problem, let me know. Thanks.

**Comment by sjbach** [comment]
Thanks.  It must be that this was fixed at some point.

**Comment by jcelliott** [comment]
I can still reproduce this on master. I also just tried with a minimal vimrc (only lusty loaded), and was still able to reproduce. That being said, I haven't actually run into this in real usage since I reported the issue ~4 years ago, so I certainly won't lose any sleep over this being closed :).

**Comment by sjbach** [comment]
Ah, I see.  The test case worked fine for me (like for ggustafsson), but I should have looked closer.  Your output is from the juggler plugin.  I checked, and it breaks for me in the same way -- thanks for commenting again.

**Comment by jcelliott** [comment]
Thanks for fixing this!
